services:
  magentic-desktop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magentic-desktop
    entrypoint: ["/bin/bash", "-c"]
    command: ["${OVERRIDE_COMMAND:-/desks/entrypoint.sh}"]
    privileged: true
    ports:
      - "3389:3389"
      - "8080:8080" 
    environment:
      - DISPLAY=:0
      - OVERRIDE_COMMAND=${OVERRIDE_COMMAND:-}
    volumes:
      - /Users/ericlaquer/Secrets:/Secrets
      - /Users/ericlaquer/Documents/GitHub:/GitHub
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /var/lib/containers:/var/lib/containers:rw
      - ./.gem:/.gem:rw
      #- ./.local/share:/home/podman/.local/share:rw
      #- ./desks/:/desks/:rw # This is a workaround to allow the noentrypoint.sh file to be overridden by the host
      #- testuser-firefox-state:/home/testuser/firefox-state
      #- coder-firefox-state:/home/coder/firefox-state
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - magentic-network

networks:
  magentic-network:
    driver: bridge

volumes:
  testuser-firefox-state:
    driver: local
  coder-firefox-state:
    driver: local
